version: '3'

services:
  consul-server-bootstrap:
    image:  consul:latest
    command: "agent -server -ui -client 0.0.0.0 -bootstrap-expect=3"
    networks:
      consul-cpx:
        aliases:
          - consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"

  consul-server-1:
    image:  consul:latest
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      consul-cpx:
        aliases:
          - consul
    depends_on:
      - consul-server-bootstrap

  consul-server-2:
    image:  consul:latest
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      consul-cpx:
        aliases:
          - consul
    depends_on:
      - consul-server-bootstrap
  
  sidecar:
    build: ./sidecar
    image: sidecar
    networks:
      - consul-cpx
    container_name: sidecar
    depends_on:
      - consul-server-bootstrap
      - consul-server-1
      - consul-server-2
      - cpx
  
nomad-server-1:
    container_name: nomad-server-1
    command: /bin/nomad agent -config=/server.hcl
    networks:
      - consul-cpx
    environment:
      NOMAD_SERVER_HTTP_PORT: 4646
      NOMAD_SERVER_RPC_PORT: 4647
      NOMAD_SERVER_SERF_PORT: 4648
      NOMAD_SERVER_ADDRESS_2: nomad-server-1:5648
      NOMAD_SERVER_ADDRESS_3: nomad-server-3:6648
      NOMAD_DATA_DIR: /tmp/nomad/data/s1
    image: rms1000watt/nomad:latest
    ports:
      - 4646:4646
      - 4647:4647
      - 4648:4648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl
    - /tmp:/tmp

  nomad-server-2:
    container_name: nomad-server-2
    command: /bin/nomad agent -config=/server.hcl
    networks:
      - consul-cpx
    environment:
      NOMAD_SERVER_HTTP_PORT: 5646
      NOMAD_SERVER_RPC_PORT: 5647
      NOMAD_SERVER_SERF_PORT: 5648
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4648
      NOMAD_SERVER_ADDRESS_3: nomad-server-3:6648
      NOMAD_DATA_DIR: /tmp/nomad/data/s2
    image: rms1000watt/nomad:latest
    ports:
      - 5646:5646
      - 5647:5647
      - 5648:5648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl
    - /tmp:/tmp
    depends_on:
    - nomad-server-1

  nomad-server-3:
    container_name: nomad-server-3
    command: /bin/nomad agent -config=/server.hcl
    networks:
      - consul-cpx
    environment:
      NOMAD_SERVER_HTTP_PORT: 6646
      NOMAD_SERVER_RPC_PORT: 6647
      NOMAD_SERVER_SERF_PORT: 6648
      NOMAD_SERVER_ADDRESS_1: nomad-server-1:4648
      NOMAD_SERVER_ADDRESS_2: nomad-server-2:5648
      NOMAD_DATA_DIR: /tmp/nomad/data/s3
    image: rms1000watt/nomad:latest
    ports:
      - 6646:6646
      - 6647:6647
      - 6648:6648
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./server.hcl.tpl:/server.hcl.tpl
    - /tmp:/tmp
    depends_on:
    - nomad-server-1

  cpx:
    image: store/citrix/netscalercpx:12.0-56.20
    networks:
      - consul-cpx
    tty: true
    ports:
      - 443
      - 22
      - 8080:8080
      - 80:80
      - 88:88
      - 161/udp
    container_name: cpx
    privileged: true
    environment:
      - EULA=yes

  web:
    image: glazeus/hostname
    networks:
      - consul-cpx
    ports:
      - 80
    depends_on:
      - consul-server-bootstrap

networks:
  consul-cpx:
