version: '3'

services:
  consul-server-bootstrap:
    image:  consul:latest
    command: "agent -server -ui -client 0.0.0.0 -bootstrap-expect=3"
    networks:
      consul-cpx:
        aliases:
          - consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"

  consul-server-1:
    image:  consul:latest
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      consul-cpx:
        aliases:
          - consul
    depends_on:
      - consul-server-bootstrap

  consul-server-2:
    image:  consul:latest
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      consul-cpx:
        aliases:
          - consul
    depends_on:
      - consul-server-bootstrap
  
  sidecar:
    build: ./sidecar
    image: sidecar
    networks:
      - consul-cpx
    container_name: sidecar
    depends_on:
      - consul-server-bootstrap
      - consul-server-1
      - consul-server-2
      - cpx
  
  registrator:
    image: gliderlabs/registrator:latest
    command: "-cleanup -resync 5 consul://consul:8500"
    networks:
      - consul-cpx
    container_name: registrator
    depends_on:
      - consul-server-bootstrap
      - consul-server-1
      - consul-server-2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  cpx:
    image: store/citrix/netscalercpx:12.0-56.20
    networks:
      - consul-cpx
    tty: true
    ports:
      - 443
      - 22
      - 8080:8080
      - 80:80
      - 88:88
      - 161/udp
    container_name: cpx
    privileged: true
    environment:
      - EULA=yes
      - lb_ip=192.168.6.2

  web:
    image: glazeus/hostname
    networks:
      - consul-cpx
    ports:
      - 80
    depends_on:
      - consul-server-bootstrap

networks:
  consul-cpx: